[package]
name = "wadescript"
version = "0.1.0"
edition = "2021"

[dependencies]
inkwell = { version = "0.5", features = ["llvm17-0"] }
backtrace = "0.3"

[lib]
name = "wadescript_runtime"
crate-type = ["staticlib"]
path = "src/runtime/lib.rs"
